### PR TITLE
add logos up to 2048 wide with square variants

### PR DESCRIPTION
**Pull request by adamralph**

### CODE REVIEW

**Comment by blairconrad** [comment]
They look pretty. I'm sure they'll be fine, but I'll give a quick go on my regular-DPI monitor (and maybe phone) later tonight, just to make sure the homepage looks right still.

I'm a little sad about having to make people who don't _need_ the large logo download it, paying for the extra pixels (about 12kB, as I measure it), but I don't think it's a huge deal. If nothing else, we can always experiment with an SVG or something later. I whipped one up last night, but didn't get around to inserting it into the web page yet).

**Comment by adamralph** [comment]
Hanselman did something of analysis and ending up going for 2x images http://www.hanselman.com/blog/SupportingHighdpiPixeldenseRetinaDisplaysLikeIPhonesOrTheIPad3WithCSSOrIMG.aspx

The post is a little old, but at that time SVG support was patchy. It may have improved now. As you say, the images are small, since they are so simple and play nicely with PNG compression. If they were big complex JPG's I'd feel worse about it.

**Comment by adamralph** [comment]
On the other hand, SVG support seems quite good now http://caniuse.com/#feat=svg

**Comment by adamralph** [comment]
Looks like some nastiness around IE 9-11 though. Perhaps simplest to stick with the 2x images for now.

**Comment by blairconrad** [comment]
Files look good on my ancient displays. One note about file size, though.
Your image creation program doesn't compress very aggressively? What would you say to using the files after running through pngout (default settings)?
Here are the changes I see.

|file                             |original size|pngoutted size|
|---------------------------------|-------------|--------------|
|fakeiteasy_logo_1024.png         |    48421 |  37154|
|fakeiteasy_logo_1024_square.png  |    50785 |  39427|
|fakeiteasy_logo_2048.png         |   109937 |  85954|
|fakeiteasy_logo_2048_square.png  |   116539 |  92390|
|fakeiteasy_logo_256.png          |     9076 |   7176|
|fakeiteasy_logo_256_square.png   |     9371 |   7446|
|fakeiteasy_logo_512.png          |    20196 |  16550|
|fakeiteasy_logo_512_square.png   |    21102 |  17318|

I'll submit a superseding PR (#14) with the adjustment, but if you prefer to use the originals, I'll not fight it, and do feel free to hit "merge" if you'd rather not wait for a round of communication.

**Comment by adamralph** [comment]
:ok_hand:

**Pull request closed without merging**
