### PR TITLE
Deployed a6417ab to 7.3.1 in docs with MkDocs 1.4.2 and mike 1.1.2

### PR DESCRIPTION
**Pull request by thomaslevesque**

### CODE REVIEW

**Comment by blairconrad** [comment]
What's with the `deploy` directory? It looks like you ran the early version of the `mike` command where I'd accidentally had a bonus "deploy" in it.

**Review by blairconrad — CHANGES_REQUESTED** [review]
What's with the `deploy` directory? It looks like you ran the early version of the `mike` command where I'd accidentally had a bonus "deploy" in it.

You want

```bash
mike deploy 7.3.1 --config-file ../FakeItEasy/mkdocs.yml --prefix docs --branch fancy-docs-updating-branch
```

**Comment by thomaslevesque** [comment]
> What's with the `deploy` directory?

I had not noticed!

> It looks like you ran the early version of the `mike` command where I'd accidentally had a bonus "deploy" in it.

Probably, yes

Will fix

**Comment by blairconrad** [comment]
Now that you got a fancy script, it is!

**Pull request closed without merging**
