### PR TITLE
change all links to https

### PR DESCRIPTION
**Pull request by adamralph**

### CODE REVIEW

**Comment by blairconrad** [comment]
Do you want to bother with the link in the README.md as well?
If not (or not at this time), I'm happy to merge.

**Comment by adamralph** [comment]
Good point - done.

**Comment by blairconrad** [comment]
Nice job.

**Comment by adamralph** [comment]
https://github.com/EMarshal deserves credit here, it was his PR that drove me to do this https://github.com/FakeItEasy/fakeiteasy.github.io/pull/17

**Comment by blairconrad** [comment]
Yep, saw his PR, and it's good. But you also deserve credit for building upon it.

**Comment by EMarshal** [comment]
Ah, good job. This is my preference as well, just don't like coming in to repos I'm new to and changing all their links without at least raising an issue first.

**Pull request merged**
