### PR TITLE
remove jetbrains banner

### PR DESCRIPTION
**Pull request by adamralph**
connects to https://github.com/FakeItEasy/FakeItEasy/issues/888

### CODE REVIEW

**Comment by blairconrad** [comment]
Nice remove of .footer.

I'm content with the changes, but feel bad merging before #884 is closed.

**Comment by adamralph** [comment]
I think we should wait until #884 is closed.

**Comment by blairconrad** [comment]
Exactly!

**Comment by adamralph** [comment]
https://github.com/FakeItEasy/FakeItEasy/issues/884 is closed 😉

**Pull request merged**
