### PR TITLE
adding logos with white backgrounds

### PR DESCRIPTION
**Pull request by blairconrad**
As noted in https://github.com/FakeItEasy/FakeItEasy/issues/391#issuecomment-72753807, logos are shown on top of backgrounds of different colours.
Providing white-backgrounded logos in case we need to shield our delicate letters.

### CODE REVIEW

**Comment by blairconrad** [comment]
Drat. I just realized that the way I made these was flawed. Look what happens if we put 2048 square on top of a black background:

https://github.com/FakeItEasy/FakeItEasy/issues/312
image

contrast with the new method:

image

I will submit a new PR tonight.

**Comment by adamralph** [comment]
what happened?

**Comment by adamralph** [comment]
The original PDF already has a white background and is already padded. It should just be a case of exporting to PNG as-is.

**Comment by blairconrad** [comment]
Oh, I took the 2048-wide image and flood filled white. Some pixels near the text became half-transparent. 

I have a python script at work that I used to use for resizing images (and trimming, and padding, and putting background colours on) that I can run over the transparent 2048 file and make pngs…

I don't know what PDF tools you use, but mine does not seem to export...

**Pull request merged**
